fedora-sysv/chkconfig

- alternatives.8
- alternatives.c
This option is supposed to be used when user wants to delete all alternatives. e.g. when you want to change the **link** (alternatives --install \<link\> \<name\> \<path\> \<priority\>).
State of this PR: just preview of intended functionality
> Introduce --remove-all option

- alternatives.c
```
Before:
[lnykryn@notas chkconfig(pretty_list)]$ alternatives --list | head -4
modules.sh	auto	/usr/share/Modules/init/modules.sh
fakeroot	auto	/usr/bin/fakeroot-tcp
mkisofs	auto	/usr/bin/genisoimage
whois	auto	/usr/bin/jwhois
After:
[lnykryn@notas chkconfig(pretty_list-M)]$ ./alternatives --list | head -4
modules.sh            	auto  	/usr/share/Modules/init/modules.sh
fakeroot              	auto  	/usr/bin/fakeroot-tcp
mkisofs               	auto  	/usr/bin/genisoimage
whois                 	auto  	/usr/bin/jwhois
```
> alternatives: prettier --list output

- alternatives.c
From `/abc//def/` to `/abc/def/`
Resolve: #1485304
> Fix issues with extra backslashes in path string

- alternatives.c
You will get this mesg when trying to do:
\# alternatives --set python /usr/bin/python2
When there is no python2, you'll get error 2 plus error mesg added by
this patch
Resolves: #1711171
> alternatives setService(): Add missing error mesg

- chkconfig.spec
- po/fur.po
fur.po: missing "\n" - blocks build
changelog: bogus dates
> Fixing typos

- leveldb.c
(cherry picked from commit 88c4e04c6aa1555980614717b7e2d4e39ed46598)
> Fix spelling of SELinux

- Makefile
Start using legacy date-stamp to remain consistent changelog
> makefile: Use rpmdev-bumpspec's legacy date option

- chkconfig.spec
> spec: sync specfile with Fedora

- alternatives.8
- alternatives.c
Right now when we are switching between alternatives or removing them,
we check if the facility (the path what user is using) is a symlink and
only refuse to remove it if it is an binary.
This commit add options --keep-foreign. With this option, alternatives
will check if the facility does not point to some other location than
altdir.
> alternatives: add --keep-foreign

- chkconfig.spec
Don't split chkconfig and alternatives in RHEL8
> spec: Revert changes introduced in Fedora

- Makefile
Sed command get version number from spec file and increment last
number by one. Work like old awk command was intended to work.
Old: 10.09 -> 10.1
New: 10.09 -> 10.10
Source: https://stackoverflow.com/questions/14348432/how-to-find-replace-and-increment-a-matched-number-with-sed-awk/14348899
> spec: Replace not working awk command with sed

- Makefile
See: https://github.com/ostreedev/ostree-rs-ext/pull/182
In https://github.com/ostreedev/ostree we generate a cryptographic
checksum over files and symlinks, and directories.
ostree does not currently perform any canonicalization on symlinks;
we'll respect and honor whatever bytes we're provided as input,
and replicate that on the target.
We're using the Rust tar crate to do tar serialization,
which has so far worked fine...except, I hit this corner case:
```
[root@cosa-devsh ~]# rpm -qf /usr/lib/systemd/systemd-sysv-install
chkconfig-1.13-2.el8.x86_64
[root@cosa-devsh ~]# ll /usr/lib/systemd/systemd-sysv-install
lrwxrwxrwx. 2 root root 24 Nov 29 18:08 /usr/lib/systemd/systemd-sysv-install -> ../../..//sbin/chkconfig
[root@cosa-devsh ~]#
```
But, using `set_link_name` to write the …
> build-sys: Ensure `systemd-sysv-install` symlink does not have `//`

- chkconfig.c
In 2014 list of services went from list of chars
to list of structs, but we forgot to update the function.
The old code was only working because the name of the service
was at the start of the struct
> chkconfig: use correct cmp function

- test-alternatives.sh
`-n doesn't work with unquoted arguments. Quote or use [[ ]].`
> test: fix ShellCheck `error[SC2070]`

- alternatives.c
Resolves: [#2203820](https://bugzilla.redhat.com/show_bug.cgi?id=2203820)
> Fix --keep-foreign when the target is missing completely

- leveldb.c
/sys/fs/cgroup/systemd is long gone:
https://systemd.io/CGROUP_DELEGATION/
Check for /run/systemd/system/ directory existence instead:
https://www.freedesktop.org/software/systemd/man/sd_booted.html
Closes fedora-sysv/chkconfig#116
> Fix systemdActive()

- alternatives.c
Alternatives are properly covered by the test suite and it passes, so this portion should be safe to merge.
> Alternatives: Fix issues found by static analyzers

- alternatives.c
> Avoid possible leaks in `readConfig()`

- Makefile
- alternatives.8
- alternatives.c
- chkconfig.spec
- po/chkconfig.pot
`ostree container commit` wipes /var and thereby erases the data in /var/lib/alternatives; the directory used to store configs/symlinks of alternatives.
/var is not a good place for storing such configs since it won't receive updates on bootc images either.  We need to move to another location.
Hence, use /etc/alternatives.admindir when running on an ostree-based system unless /var/lib/alternatives is already present; a user may have worked around the problem.  This way we enable alternatives to work on ostree-based systems without breaking backwards compat.
Fixes: #9
> ostree: move admindir to /etc/alternatives.admindir

- Makefile
- alternatives.c
- chkconfig.spec
After https://fedoraproject.org/wiki/Changes/Unify_bin_and_sbin, various rpms change paths from /usr/sbin to /usr/bin. If we're built in an environment where %_sbindir==%_bindir, allow paths to differ in the prefix.
Tested by reverting the patch to move paths in iptables-legacy back to /usr/sbin [1]. The subsequent rpm installs fine both when /usr/sbin is a symlink (new installs) and a directory (upgrades).
This approach is bit of a hack, but it also seems quite safe, because it doesn't change the stored data in any way, it just suppresses two error checks.
[1] https://src.fedoraproject.org/rpms/iptables/c/43696a4be35ecb64b596d1db368cb736a91316e8
> Allow paths with /usr/sbin and /usr/bin as equivalent

- .github/workflows/differential-shellcheck.yml
```
Warning:  git: base SHA1 (0000000000000000000000000000000000000000) doesn't exist. Make sure that the base branch is up-to-date.
```
> ci: fix Differential ShellCheck workflow
